/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Shop Helper
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetTask200,
  HTTPValidationError,
  N8nCallback200,
  N8nCallbackBody,
  StartWorkflow200,
  StartWorkflowBody
} from '.././model';

import { customInstance } from '.././mutator/custom-instance';
import type { ErrorType , BodyType } from '.././mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Start Workflow
 */
export const startWorkflow = (
    startWorkflowBody: BodyType<StartWorkflowBody>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<StartWorkflow200>(
      {url: `/n8n-test/start`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: startWorkflowBody, signal
    },
      options);
    }
  


export const getStartWorkflowMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startWorkflow>>, TError,{data: BodyType<StartWorkflowBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof startWorkflow>>, TError,{data: BodyType<StartWorkflowBody>}, TContext> => {

const mutationKey = ['startWorkflow'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startWorkflow>>, {data: BodyType<StartWorkflowBody>}> = (props) => {
          const {data} = props ?? {};

          return  startWorkflow(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type StartWorkflowMutationResult = NonNullable<Awaited<ReturnType<typeof startWorkflow>>>
    export type StartWorkflowMutationBody = BodyType<StartWorkflowBody>
    export type StartWorkflowMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Start Workflow
 */
export const useStartWorkflow = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startWorkflow>>, TError,{data: BodyType<StartWorkflowBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startWorkflow>>,
        TError,
        {data: BodyType<StartWorkflowBody>},
        TContext
      > => {
      return useMutation(getStartWorkflowMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Task
 */
export const getTask = (
    taskId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetTask200>(
      {url: `/n8n-test/tasks/${taskId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetTaskQueryKey = (taskId: string,) => {
    return [
    `/n8n-test/tasks/${taskId}`
    ] as const;
    }

    
export const getGetTaskQueryOptions = <TData = Awaited<ReturnType<typeof getTask>>, TError = ErrorType<HTTPValidationError>>(taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTaskQueryKey(taskId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTask>>> = ({ signal }) => getTask(taskId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(taskId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTaskQueryResult = NonNullable<Awaited<ReturnType<typeof getTask>>>
export type GetTaskQueryError = ErrorType<HTTPValidationError>


export function useGetTask<TData = Awaited<ReturnType<typeof getTask>>, TError = ErrorType<HTTPValidationError>>(
 taskId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTask>>,
          TError,
          Awaited<ReturnType<typeof getTask>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTask<TData = Awaited<ReturnType<typeof getTask>>, TError = ErrorType<HTTPValidationError>>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTask>>,
          TError,
          Awaited<ReturnType<typeof getTask>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTask<TData = Awaited<ReturnType<typeof getTask>>, TError = ErrorType<HTTPValidationError>>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Task
 */

export function useGetTask<TData = Awaited<ReturnType<typeof getTask>>, TError = ErrorType<HTTPValidationError>>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTaskQueryOptions(taskId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary N8N Callback
 */
export const n8nCallback = (
    taskId: string,
    n8nCallbackBody: BodyType<N8nCallbackBody>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<N8nCallback200>(
      {url: `/n8n-test/n8n-callback/${taskId}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: n8nCallbackBody, signal
    },
      options);
    }
  


export const getN8nCallbackMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof n8nCallback>>, TError,{taskId: string;data: BodyType<N8nCallbackBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof n8nCallback>>, TError,{taskId: string;data: BodyType<N8nCallbackBody>}, TContext> => {

const mutationKey = ['n8nCallback'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof n8nCallback>>, {taskId: string;data: BodyType<N8nCallbackBody>}> = (props) => {
          const {taskId,data} = props ?? {};

          return  n8nCallback(taskId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type N8nCallbackMutationResult = NonNullable<Awaited<ReturnType<typeof n8nCallback>>>
    export type N8nCallbackMutationBody = BodyType<N8nCallbackBody>
    export type N8nCallbackMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary N8N Callback
 */
export const useN8nCallback = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof n8nCallback>>, TError,{taskId: string;data: BodyType<N8nCallbackBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof n8nCallback>>,
        TError,
        {taskId: string;data: BodyType<N8nCallbackBody>},
        TContext
      > => {
      return useMutation(getN8nCallbackMutationOptions(options), queryClient);
    }
    