/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Shop Helper
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Start Workflow
 */
export const N8nTestStartWorkflowBody = zod.record(zod.string(), zod.unknown())

export const N8nTestStartWorkflowResponse = zod.record(zod.string(), zod.unknown())

/**
 * @summary Get Task
 */
export const N8nTestGetTaskParams = zod.object({
  "task_id": zod.string()
})

export const N8nTestGetTaskResponse = zod.record(zod.string(), zod.unknown())

/**
 * @summary Callback
 */
export const N8nTestCallbackBody = zod.record(zod.string(), zod.unknown())

export const N8nTestCallbackResponse = zod.record(zod.string(), zod.unknown())

