/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Shop Helper
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetMyOrgsParams,
  HTTPValidationError,
  OrgCreate,
  OrgPublic,
  OrgUpdate,
  PaginatedResponseOrgPublic
} from '.././model';

import { customInstance } from '.././mutator/custom-instance';
import type { ErrorType , BodyType } from '.././mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Create a new organization. Creator becomes owner.

Args:
    org_in (OrgCreate): The organization data.
    current_user (User): The current authenticated user.
    session (SessionDep): The database session.

Returns:
    OrgPublic: The created organization.

Raises:
    HTTPException: 409 if the organization name is already registered.
 * @summary Create Org
 */
export const createOrg = (
    orgCreate: BodyType<OrgCreate>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<OrgPublic>(
      {url: `/orgs/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: orgCreate, signal
    },
      options);
    }
  


export const getCreateOrgMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOrg>>, TError,{data: BodyType<OrgCreate>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createOrg>>, TError,{data: BodyType<OrgCreate>}, TContext> => {

const mutationKey = ['createOrg'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createOrg>>, {data: BodyType<OrgCreate>}> = (props) => {
          const {data} = props ?? {};

          return  createOrg(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateOrgMutationResult = NonNullable<Awaited<ReturnType<typeof createOrg>>>
    export type CreateOrgMutationBody = BodyType<OrgCreate>
    export type CreateOrgMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Org
 */
export const useCreateOrg = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOrg>>, TError,{data: BodyType<OrgCreate>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createOrg>>,
        TError,
        {data: BodyType<OrgCreate>},
        TContext
      > => {
      return useMutation(getCreateOrgMutationOptions(options), queryClient);
    }
    /**
 * Get organizations the current user is a member of.

Args:
    current_user (User): The current authenticated user.
    pagination (PaginationParams): The pagination parameters.
    session (SessionDep): The database session.

Returns:
    PaginatedResponse[OrgPublic]: The paginated list of organizations.
 * @summary Get My Orgs
 */
export const getMyOrgs = (
    params?: GetMyOrgsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PaginatedResponseOrgPublic>(
      {url: `/orgs/`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetMyOrgsQueryKey = (params?: GetMyOrgsParams,) => {
    return [
    `/orgs/`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetMyOrgsQueryOptions = <TData = Awaited<ReturnType<typeof getMyOrgs>>, TError = ErrorType<HTTPValidationError>>(params?: GetMyOrgsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyOrgs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyOrgsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyOrgs>>> = ({ signal }) => getMyOrgs(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyOrgs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyOrgsQueryResult = NonNullable<Awaited<ReturnType<typeof getMyOrgs>>>
export type GetMyOrgsQueryError = ErrorType<HTTPValidationError>


export function useGetMyOrgs<TData = Awaited<ReturnType<typeof getMyOrgs>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  GetMyOrgsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyOrgs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyOrgs>>,
          TError,
          Awaited<ReturnType<typeof getMyOrgs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyOrgs<TData = Awaited<ReturnType<typeof getMyOrgs>>, TError = ErrorType<HTTPValidationError>>(
 params?: GetMyOrgsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyOrgs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyOrgs>>,
          TError,
          Awaited<ReturnType<typeof getMyOrgs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyOrgs<TData = Awaited<ReturnType<typeof getMyOrgs>>, TError = ErrorType<HTTPValidationError>>(
 params?: GetMyOrgsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyOrgs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get My Orgs
 */

export function useGetMyOrgs<TData = Awaited<ReturnType<typeof getMyOrgs>>, TError = ErrorType<HTTPValidationError>>(
 params?: GetMyOrgsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyOrgs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyOrgsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get an organization by ID. Member access only.

Args:
    org_id (UUID): The organization ID.
    org_member (tuple[User, OrgUser]): The current user and their org membership.
    session (SessionDep): The database session.

Returns:
    OrgPublic: The organization.

Raises:
    HTTPException: 404 if the organization does not exist.
 * @summary Get Org
 */
export const getOrg = (
    orgId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<OrgPublic>(
      {url: `/orgs/${orgId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetOrgQueryKey = (orgId: string,) => {
    return [
    `/orgs/${orgId}`
    ] as const;
    }

    
export const getGetOrgQueryOptions = <TData = Awaited<ReturnType<typeof getOrg>>, TError = ErrorType<HTTPValidationError>>(orgId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrg>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrgQueryKey(orgId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrg>>> = ({ signal }) => getOrg(orgId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(orgId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrg>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOrgQueryResult = NonNullable<Awaited<ReturnType<typeof getOrg>>>
export type GetOrgQueryError = ErrorType<HTTPValidationError>


export function useGetOrg<TData = Awaited<ReturnType<typeof getOrg>>, TError = ErrorType<HTTPValidationError>>(
 orgId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrg>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrg>>,
          TError,
          Awaited<ReturnType<typeof getOrg>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrg<TData = Awaited<ReturnType<typeof getOrg>>, TError = ErrorType<HTTPValidationError>>(
 orgId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrg>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrg>>,
          TError,
          Awaited<ReturnType<typeof getOrg>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrg<TData = Awaited<ReturnType<typeof getOrg>>, TError = ErrorType<HTTPValidationError>>(
 orgId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrg>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Org
 */

export function useGetOrg<TData = Awaited<ReturnType<typeof getOrg>>, TError = ErrorType<HTTPValidationError>>(
 orgId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrg>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOrgQueryOptions(orgId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update an organization. Admin+ only.

Args:
    org_id (UUID): The organization ID.
    org_in (OrgUpdate): The update data.
    org_admin (tuple[User, OrgUser]): The current user and their org membership.
    session (SessionDep): The database session.

Returns:
    OrgPublic: The updated organization.

Raises:
    HTTPException: 404 if the organization does not exist.
    HTTPException: 409 if the organization name is already registered.
 * @summary Update Org
 */
export const updateOrg = (
    orgId: string,
    orgUpdate: BodyType<OrgUpdate>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<OrgPublic>(
      {url: `/orgs/${orgId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: orgUpdate, signal
    },
      options);
    }
  


export const getUpdateOrgMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOrg>>, TError,{orgId: string;data: BodyType<OrgUpdate>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateOrg>>, TError,{orgId: string;data: BodyType<OrgUpdate>}, TContext> => {

const mutationKey = ['updateOrg'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateOrg>>, {orgId: string;data: BodyType<OrgUpdate>}> = (props) => {
          const {orgId,data} = props ?? {};

          return  updateOrg(orgId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateOrgMutationResult = NonNullable<Awaited<ReturnType<typeof updateOrg>>>
    export type UpdateOrgMutationBody = BodyType<OrgUpdate>
    export type UpdateOrgMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Org
 */
export const useUpdateOrg = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOrg>>, TError,{orgId: string;data: BodyType<OrgUpdate>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateOrg>>,
        TError,
        {orgId: string;data: BodyType<OrgUpdate>},
        TContext
      > => {
      return useMutation(getUpdateOrgMutationOptions(options), queryClient);
    }
    /**
 * Delete an organization. Owner only.

Args:
    org_id (UUID): The organization ID.
    org_owner (tuple[User, OrgUser]): The current user and their org membership.
    session (SessionDep): The database session.

Raises:
    HTTPException: 404 if the organization does not exist.
 * @summary Delete Org
 */
export const deleteOrg = (
    orgId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/orgs/${orgId}`, method: 'DELETE', signal
    },
      options);
    }
  


export const getDeleteOrgMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOrg>>, TError,{orgId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteOrg>>, TError,{orgId: string}, TContext> => {

const mutationKey = ['deleteOrg'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteOrg>>, {orgId: string}> = (props) => {
          const {orgId} = props ?? {};

          return  deleteOrg(orgId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteOrgMutationResult = NonNullable<Awaited<ReturnType<typeof deleteOrg>>>
    
    export type DeleteOrgMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Delete Org
 */
export const useDeleteOrg = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOrg>>, TError,{orgId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteOrg>>,
        TError,
        {orgId: string},
        TContext
      > => {
      return useMutation(getDeleteOrgMutationOptions(options), queryClient);
    }
    