/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Shop Helper
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Create a new organization. Creator becomes owner.

Args:
    org_in (OrgCreate): The organization data.
    current_user (User): The current authenticated user.
    session (SessionDep): The database session.

Returns:
    OrgPublic: The created organization.

Raises:
    HTTPException: 409 if the organization name is already registered.
 * @summary Create Org
 */
export const orgsCreateOrgBodyNameMax = 255;



export const OrgsCreateOrgBody = zod.object({
  "name": zod.string().min(1).max(orgsCreateOrgBodyNameMax)
}).describe('Schema for creating a new organization.')

/**
 * Get organizations the current user is a member of with nested projects.

Args:
    current_user (User): The current authenticated user.
    pagination (PaginationParams): The pagination parameters.
    session (SessionDep): The database session.

Returns:
    PaginatedResponse[OrgWithProjects]: The paginated list of organizations with projects.
 * @summary Get My Orgs
 */
export const orgsGetMyOrgsQueryOffsetDefault = 0;
export const orgsGetMyOrgsQueryOffsetMin = 0;

export const orgsGetMyOrgsQueryLimitDefault = 50;
export const orgsGetMyOrgsQueryLimitMax = 100;



export const OrgsGetMyOrgsQueryParams = zod.object({
  "offset": zod.number().min(orgsGetMyOrgsQueryOffsetMin).default(orgsGetMyOrgsQueryOffsetDefault),
  "limit": zod.number().min(1).max(orgsGetMyOrgsQueryLimitMax).default(orgsGetMyOrgsQueryLimitDefault)
})

export const OrgsGetMyOrgsResponse = zod.unknown()

/**
 * Get an organization by ID. Member access only.

Args:
    org_id (UUID): The organization ID.
    org_member (tuple[User, OrgUser]): The current user and their org membership.
    session (SessionDep): The database session.

Returns:
    OrgPublic: The organization.

Raises:
    HTTPException: 404 if the organization does not exist.
 * @summary Get Org
 */
export const OrgsGetOrgParams = zod.object({
  "org_id": zod.string().uuid()
})

export const OrgsGetOrgResponse = zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "credits": zod.number(),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({}),
  "created_by": zod.string().uuid(),
  "updated_by": zod.string().uuid()
}).describe('Schema for returning organization data to the client.')

/**
 * Update an organization. Admin+ only.

Args:
    org_id (UUID): The organization ID.
    org_in (OrgUpdate): The update data.
    org_admin (tuple[User, OrgUser]): The current user and their org membership.
    session (SessionDep): The database session.

Returns:
    OrgPublic: The updated organization.

Raises:
    HTTPException: 404 if the organization does not exist.
    HTTPException: 409 if the organization name is already registered.
 * @summary Update Org
 */
export const OrgsUpdateOrgParams = zod.object({
  "org_id": zod.string().uuid()
})

export const orgsUpdateOrgBodyNameOneMax = 255;

export const orgsUpdateOrgBodyCreditsOneMin = 0;



export const OrgsUpdateOrgBody = zod.object({
  "name": zod.union([zod.string().min(1).max(orgsUpdateOrgBodyNameOneMax),zod.null()]).optional(),
  "credits": zod.union([zod.number().min(orgsUpdateOrgBodyCreditsOneMin),zod.null()]).optional()
}).describe('Schema for updating an organization.')

export const OrgsUpdateOrgResponse = zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "credits": zod.number(),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({}),
  "created_by": zod.string().uuid(),
  "updated_by": zod.string().uuid()
}).describe('Schema for returning organization data to the client.')

/**
 * Delete an organization. Owner only.

Args:
    org_id (UUID): The organization ID.
    org_owner (tuple[User, OrgUser]): The current user and their org membership.
    session (SessionDep): The database session.

Raises:
    HTTPException: 404 if the organization does not exist.
 * @summary Delete Org
 */
export const OrgsDeleteOrgParams = zod.object({
  "org_id": zod.string().uuid()
})

