/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Shop Helper
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetOrgMembersParams,
  HTTPValidationError,
  OrgUserCreate,
  OrgUserPublic,
  OrgUserUpdate,
  PaginatedResponseOrgUserPublic
} from '.././model';

import { customInstance } from '.././mutator/custom-instance';
import type { ErrorType , BodyType } from '.././mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Add a member to the organization. Admin+ only.

Args:
    org_id (UUID): The organization ID.
    org_user_in (OrgUserCreate): The member data.
    org_admin (tuple[User, OrgUser]): The current user and their org membership.
    session (SessionDep): The database session.

Returns:
    OrgUserPublic: The created org membership.

Raises:
    HTTPException: 400 if org_id mismatch.
    HTTPException: 404 if user or role does not exist.
    HTTPException: 409 if the user is already a member.
 * @summary Add Org Member
 */
export const addOrgMember = (
    orgId: string,
    orgUserCreate: BodyType<OrgUserCreate>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<OrgUserPublic>(
      {url: `/orgs/${orgId}/members`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: orgUserCreate, signal
    },
      options);
    }
  


export const getAddOrgMemberMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addOrgMember>>, TError,{orgId: string;data: BodyType<OrgUserCreate>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof addOrgMember>>, TError,{orgId: string;data: BodyType<OrgUserCreate>}, TContext> => {

const mutationKey = ['addOrgMember'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addOrgMember>>, {orgId: string;data: BodyType<OrgUserCreate>}> = (props) => {
          const {orgId,data} = props ?? {};

          return  addOrgMember(orgId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AddOrgMemberMutationResult = NonNullable<Awaited<ReturnType<typeof addOrgMember>>>
    export type AddOrgMemberMutationBody = BodyType<OrgUserCreate>
    export type AddOrgMemberMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Add Org Member
 */
export const useAddOrgMember = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addOrgMember>>, TError,{orgId: string;data: BodyType<OrgUserCreate>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addOrgMember>>,
        TError,
        {orgId: string;data: BodyType<OrgUserCreate>},
        TContext
      > => {
      return useMutation(getAddOrgMemberMutationOptions(options), queryClient);
    }
    /**
 * List organization members. Member access.

Args:
    org_id (UUID): The organization ID.
    org_member (tuple[User, OrgUser]): The current user and their org membership.
    pagination (PaginationParams): The pagination parameters.
    session (SessionDep): The database session.

Returns:
    PaginatedResponse[OrgUserPublic]: The paginated list of members.
 * @summary Get Org Members
 */
export const getOrgMembers = (
    orgId: string,
    params?: GetOrgMembersParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PaginatedResponseOrgUserPublic>(
      {url: `/orgs/${orgId}/members`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetOrgMembersQueryKey = (orgId: string,
    params?: GetOrgMembersParams,) => {
    return [
    `/orgs/${orgId}/members`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetOrgMembersQueryOptions = <TData = Awaited<ReturnType<typeof getOrgMembers>>, TError = ErrorType<HTTPValidationError>>(orgId: string,
    params?: GetOrgMembersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrgMembers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrgMembersQueryKey(orgId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrgMembers>>> = ({ signal }) => getOrgMembers(orgId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(orgId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrgMembers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOrgMembersQueryResult = NonNullable<Awaited<ReturnType<typeof getOrgMembers>>>
export type GetOrgMembersQueryError = ErrorType<HTTPValidationError>


export function useGetOrgMembers<TData = Awaited<ReturnType<typeof getOrgMembers>>, TError = ErrorType<HTTPValidationError>>(
 orgId: string,
    params: undefined |  GetOrgMembersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrgMembers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrgMembers>>,
          TError,
          Awaited<ReturnType<typeof getOrgMembers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrgMembers<TData = Awaited<ReturnType<typeof getOrgMembers>>, TError = ErrorType<HTTPValidationError>>(
 orgId: string,
    params?: GetOrgMembersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrgMembers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrgMembers>>,
          TError,
          Awaited<ReturnType<typeof getOrgMembers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrgMembers<TData = Awaited<ReturnType<typeof getOrgMembers>>, TError = ErrorType<HTTPValidationError>>(
 orgId: string,
    params?: GetOrgMembersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrgMembers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Org Members
 */

export function useGetOrgMembers<TData = Awaited<ReturnType<typeof getOrgMembers>>, TError = ErrorType<HTTPValidationError>>(
 orgId: string,
    params?: GetOrgMembersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrgMembers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOrgMembersQueryOptions(orgId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get specific member details. Member access.

Args:
    org_id (UUID): The organization ID.
    user_id (UUID): The user ID.
    org_member (tuple[User, OrgUser]): The current user and their org membership.
    session (SessionDep): The database session.

Returns:
    OrgUserPublic: The org membership.

Raises:
    HTTPException: 404 if the member is not found.
 * @summary Get Org Member
 */
export const getOrgMember = (
    orgId: string,
    userId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<OrgUserPublic>(
      {url: `/orgs/${orgId}/members/${userId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetOrgMemberQueryKey = (orgId: string,
    userId: string,) => {
    return [
    `/orgs/${orgId}/members/${userId}`
    ] as const;
    }

    
export const getGetOrgMemberQueryOptions = <TData = Awaited<ReturnType<typeof getOrgMember>>, TError = ErrorType<HTTPValidationError>>(orgId: string,
    userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrgMember>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrgMemberQueryKey(orgId,userId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrgMember>>> = ({ signal }) => getOrgMember(orgId,userId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(orgId && userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrgMember>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOrgMemberQueryResult = NonNullable<Awaited<ReturnType<typeof getOrgMember>>>
export type GetOrgMemberQueryError = ErrorType<HTTPValidationError>


export function useGetOrgMember<TData = Awaited<ReturnType<typeof getOrgMember>>, TError = ErrorType<HTTPValidationError>>(
 orgId: string,
    userId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrgMember>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrgMember>>,
          TError,
          Awaited<ReturnType<typeof getOrgMember>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrgMember<TData = Awaited<ReturnType<typeof getOrgMember>>, TError = ErrorType<HTTPValidationError>>(
 orgId: string,
    userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrgMember>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrgMember>>,
          TError,
          Awaited<ReturnType<typeof getOrgMember>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrgMember<TData = Awaited<ReturnType<typeof getOrgMember>>, TError = ErrorType<HTTPValidationError>>(
 orgId: string,
    userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrgMember>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Org Member
 */

export function useGetOrgMember<TData = Awaited<ReturnType<typeof getOrgMember>>, TError = ErrorType<HTTPValidationError>>(
 orgId: string,
    userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrgMember>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOrgMemberQueryOptions(orgId,userId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update member's role. Admin+ only.

Args:
    org_id (UUID): The organization ID.
    user_id (UUID): The user ID.
    org_user_in (OrgUserUpdate): The update data.
    org_admin (tuple[User, OrgUser]): The current user and their org membership.
    session (SessionDep): The database session.

Returns:
    OrgUserPublic: The updated org membership.

Raises:
    HTTPException: 404 if the member or role does not exist.
    HTTPException: 400 if removing last owner.
 * @summary Update Org Member Role
 */
export const updateOrgMemberRole = (
    orgId: string,
    userId: string,
    orgUserUpdate: BodyType<OrgUserUpdate>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<OrgUserPublic>(
      {url: `/orgs/${orgId}/members/${userId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: orgUserUpdate, signal
    },
      options);
    }
  


export const getUpdateOrgMemberRoleMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOrgMemberRole>>, TError,{orgId: string;userId: string;data: BodyType<OrgUserUpdate>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateOrgMemberRole>>, TError,{orgId: string;userId: string;data: BodyType<OrgUserUpdate>}, TContext> => {

const mutationKey = ['updateOrgMemberRole'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateOrgMemberRole>>, {orgId: string;userId: string;data: BodyType<OrgUserUpdate>}> = (props) => {
          const {orgId,userId,data} = props ?? {};

          return  updateOrgMemberRole(orgId,userId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateOrgMemberRoleMutationResult = NonNullable<Awaited<ReturnType<typeof updateOrgMemberRole>>>
    export type UpdateOrgMemberRoleMutationBody = BodyType<OrgUserUpdate>
    export type UpdateOrgMemberRoleMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Org Member Role
 */
export const useUpdateOrgMemberRole = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOrgMemberRole>>, TError,{orgId: string;userId: string;data: BodyType<OrgUserUpdate>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateOrgMemberRole>>,
        TError,
        {orgId: string;userId: string;data: BodyType<OrgUserUpdate>},
        TContext
      > => {
      return useMutation(getUpdateOrgMemberRoleMutationOptions(options), queryClient);
    }
    /**
 * Remove member from organization. Admin+ only. Last-owner protection applies.

Args:
    org_id (UUID): The organization ID.
    user_id (UUID): The user ID.
    org_admin (tuple[User, OrgUser]): The current user and their org membership.
    session (SessionDep): The database session.

Raises:
    HTTPException: 404 if the member does not exist.
    HTTPException: 400 if removing last owner.
 * @summary Remove Org Member
 */
export const removeOrgMember = (
    orgId: string,
    userId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/orgs/${orgId}/members/${userId}`, method: 'DELETE', signal
    },
      options);
    }
  


export const getRemoveOrgMemberMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeOrgMember>>, TError,{orgId: string;userId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof removeOrgMember>>, TError,{orgId: string;userId: string}, TContext> => {

const mutationKey = ['removeOrgMember'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeOrgMember>>, {orgId: string;userId: string}> = (props) => {
          const {orgId,userId} = props ?? {};

          return  removeOrgMember(orgId,userId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RemoveOrgMemberMutationResult = NonNullable<Awaited<ReturnType<typeof removeOrgMember>>>
    
    export type RemoveOrgMemberMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Remove Org Member
 */
export const useRemoveOrgMember = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeOrgMember>>, TError,{orgId: string;userId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeOrgMember>>,
        TError,
        {orgId: string;userId: string},
        TContext
      > => {
      return useMutation(getRemoveOrgMemberMutationOptions(options), queryClient);
    }
    