/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Shop Helper
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Add a member to the organization. Admin+ only.

Args:
    org_id (UUID): The organization ID.
    org_user_in (OrgUserCreate): The member data.
    org_admin (tuple[User, OrgUser]): The current user and their org membership.
    session (SessionDep): The database session.

Returns:
    OrgUserPublic: The created org membership.

Raises:
    HTTPException: 400 if org_id mismatch.
    HTTPException: 404 if user or role does not exist.
    HTTPException: 409 if the user is already a member.
 * @summary Add Org Member
 */
export const OrgMembersAddOrgMemberParams = zod.object({
  "org_id": zod.string().uuid()
})

export const OrgMembersAddOrgMemberBody = zod.object({
  "user_id": zod.string().uuid(),
  "org_id": zod.string().uuid(),
  "role_id": zod.string().uuid()
}).describe('Schema for adding a member to an organization.')

/**
 * List organization members. Member access.

Args:
    org_id (UUID): The organization ID.
    org_member (tuple[User, OrgUser]): The current user and their org membership.
    pagination (PaginationParams): The pagination parameters.
    session (SessionDep): The database session.

Returns:
    PaginatedResponse[OrgUserPublic]: The paginated list of members.
 * @summary Get Org Members
 */
export const OrgMembersGetOrgMembersParams = zod.object({
  "org_id": zod.string().uuid()
})

export const orgMembersGetOrgMembersQueryOffsetDefault = 0;
export const orgMembersGetOrgMembersQueryOffsetMin = 0;

export const orgMembersGetOrgMembersQueryLimitDefault = 50;
export const orgMembersGetOrgMembersQueryLimitMax = 100;



export const OrgMembersGetOrgMembersQueryParams = zod.object({
  "offset": zod.number().min(orgMembersGetOrgMembersQueryOffsetMin).default(orgMembersGetOrgMembersQueryOffsetDefault),
  "limit": zod.number().min(1).max(orgMembersGetOrgMembersQueryLimitMax).default(orgMembersGetOrgMembersQueryLimitDefault)
})

export const OrgMembersGetOrgMembersResponse = zod.unknown()

/**
 * Get specific member details. Member access.

Args:
    org_id (UUID): The organization ID.
    user_id (UUID): The user ID.
    org_member (tuple[User, OrgUser]): The current user and their org membership.
    session (SessionDep): The database session.

Returns:
    OrgUserPublic: The org membership.

Raises:
    HTTPException: 404 if the member is not found.
 * @summary Get Org Member
 */
export const OrgMembersGetOrgMemberParams = zod.object({
  "org_id": zod.string().uuid(),
  "user_id": zod.string().uuid()
})

export const OrgMembersGetOrgMemberResponse = zod.object({
  "id": zod.string().uuid(),
  "user_id": zod.string().uuid(),
  "org_id": zod.string().uuid(),
  "role_id": zod.string().uuid(),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({}),
  "created_by": zod.string().uuid(),
  "updated_by": zod.string().uuid()
}).describe('Schema for returning org membership data to the client.')

/**
 * Update member's role. Admin+ only.

Args:
    org_id (UUID): The organization ID.
    user_id (UUID): The user ID.
    org_user_in (OrgUserUpdate): The update data.
    org_admin (tuple[User, OrgUser]): The current user and their org membership.
    session (SessionDep): The database session.

Returns:
    OrgUserPublic: The updated org membership.

Raises:
    HTTPException: 404 if the member or role does not exist.
    HTTPException: 400 if removing last owner.
 * @summary Update Org Member Role
 */
export const OrgMembersUpdateOrgMemberRoleParams = zod.object({
  "org_id": zod.string().uuid(),
  "user_id": zod.string().uuid()
})

export const OrgMembersUpdateOrgMemberRoleBody = zod.object({
  "role_id": zod.string().uuid()
}).describe('Schema for updating a member\'s role.')

export const OrgMembersUpdateOrgMemberRoleResponse = zod.object({
  "id": zod.string().uuid(),
  "user_id": zod.string().uuid(),
  "org_id": zod.string().uuid(),
  "role_id": zod.string().uuid(),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({}),
  "created_by": zod.string().uuid(),
  "updated_by": zod.string().uuid()
}).describe('Schema for returning org membership data to the client.')

/**
 * Remove member from organization. Admin+ only. Last-owner protection applies.

Args:
    org_id (UUID): The organization ID.
    user_id (UUID): The user ID.
    org_admin (tuple[User, OrgUser]): The current user and their org membership.
    session (SessionDep): The database session.

Raises:
    HTTPException: 404 if the member does not exist.
    HTTPException: 400 if removing last owner.
 * @summary Remove Org Member
 */
export const OrgMembersRemoveOrgMemberParams = zod.object({
  "org_id": zod.string().uuid(),
  "user_id": zod.string().uuid()
})

