/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Shop Helper
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AgentProjectTypeCreate,
  AgentProjectTypePublic,
  GetAgentProjectTypesParams,
  HTTPValidationError,
  PaginatedResponseAgentProjectTypePublic
} from '.././model';

import { customInstance } from '.././mutator/custom-instance';
import type { ErrorType , BodyType } from '.././mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Create a new agent-project type relationship. Superuser only.

Args:
    apt_in (AgentProjectTypeCreate): The relationship data.
    current_superuser (User): The current superuser.
    session (SessionDep): The database session.

Returns:
    AgentProjectTypePublic: The created relationship.

Raises:
    HTTPException: 404 if agent or project type does not exist.
    HTTPException: 409 if the relationship already exists.
 * @summary Create Agent Project Type
 */
export const createAgentProjectType = (
    agentProjectTypeCreate: BodyType<AgentProjectTypeCreate>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AgentProjectTypePublic>(
      {url: `/agent-project-types/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: agentProjectTypeCreate, signal
    },
      options);
    }
  


export const getCreateAgentProjectTypeMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAgentProjectType>>, TError,{data: BodyType<AgentProjectTypeCreate>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createAgentProjectType>>, TError,{data: BodyType<AgentProjectTypeCreate>}, TContext> => {

const mutationKey = ['createAgentProjectType'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createAgentProjectType>>, {data: BodyType<AgentProjectTypeCreate>}> = (props) => {
          const {data} = props ?? {};

          return  createAgentProjectType(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateAgentProjectTypeMutationResult = NonNullable<Awaited<ReturnType<typeof createAgentProjectType>>>
    export type CreateAgentProjectTypeMutationBody = BodyType<AgentProjectTypeCreate>
    export type CreateAgentProjectTypeMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Agent Project Type
 */
export const useCreateAgentProjectType = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAgentProjectType>>, TError,{data: BodyType<AgentProjectTypeCreate>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createAgentProjectType>>,
        TError,
        {data: BodyType<AgentProjectTypeCreate>},
        TContext
      > => {
      return useMutation(getCreateAgentProjectTypeMutationOptions(options), queryClient);
    }
    /**
 * Get a paginated list of agent-project type relationships. Superuser only.

Args:
    current_superuser (User): The current superuser.
    pagination (PaginationParams): The pagination parameters.
    session (SessionDep): The database session.

Returns:
    PaginatedResponse[AgentProjectTypePublic]: The paginated list of relationships.
 * @summary Get Agent Project Types
 */
export const getAgentProjectTypes = (
    params?: GetAgentProjectTypesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PaginatedResponseAgentProjectTypePublic>(
      {url: `/agent-project-types/`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAgentProjectTypesQueryKey = (params?: GetAgentProjectTypesParams,) => {
    return [
    `/agent-project-types/`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetAgentProjectTypesQueryOptions = <TData = Awaited<ReturnType<typeof getAgentProjectTypes>>, TError = ErrorType<HTTPValidationError>>(params?: GetAgentProjectTypesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentProjectTypes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAgentProjectTypesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAgentProjectTypes>>> = ({ signal }) => getAgentProjectTypes(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAgentProjectTypes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAgentProjectTypesQueryResult = NonNullable<Awaited<ReturnType<typeof getAgentProjectTypes>>>
export type GetAgentProjectTypesQueryError = ErrorType<HTTPValidationError>


export function useGetAgentProjectTypes<TData = Awaited<ReturnType<typeof getAgentProjectTypes>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  GetAgentProjectTypesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentProjectTypes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAgentProjectTypes>>,
          TError,
          Awaited<ReturnType<typeof getAgentProjectTypes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAgentProjectTypes<TData = Awaited<ReturnType<typeof getAgentProjectTypes>>, TError = ErrorType<HTTPValidationError>>(
 params?: GetAgentProjectTypesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentProjectTypes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAgentProjectTypes>>,
          TError,
          Awaited<ReturnType<typeof getAgentProjectTypes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAgentProjectTypes<TData = Awaited<ReturnType<typeof getAgentProjectTypes>>, TError = ErrorType<HTTPValidationError>>(
 params?: GetAgentProjectTypesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentProjectTypes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Agent Project Types
 */

export function useGetAgentProjectTypes<TData = Awaited<ReturnType<typeof getAgentProjectTypes>>, TError = ErrorType<HTTPValidationError>>(
 params?: GetAgentProjectTypesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentProjectTypes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAgentProjectTypesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get an agent-project type relationship by ID. Superuser only.

Args:
    apt_id (UUID): The relationship ID.
    current_superuser (User): The current superuser.
    session (SessionDep): The database session.

Returns:
    AgentProjectTypePublic: The relationship.

Raises:
    HTTPException: 404 if the relationship does not exist.
 * @summary Get Agent Project Type
 */
export const getAgentProjectType = (
    aptId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AgentProjectTypePublic>(
      {url: `/agent-project-types/${aptId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetAgentProjectTypeQueryKey = (aptId: string,) => {
    return [
    `/agent-project-types/${aptId}`
    ] as const;
    }

    
export const getGetAgentProjectTypeQueryOptions = <TData = Awaited<ReturnType<typeof getAgentProjectType>>, TError = ErrorType<HTTPValidationError>>(aptId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentProjectType>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAgentProjectTypeQueryKey(aptId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAgentProjectType>>> = ({ signal }) => getAgentProjectType(aptId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(aptId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAgentProjectType>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAgentProjectTypeQueryResult = NonNullable<Awaited<ReturnType<typeof getAgentProjectType>>>
export type GetAgentProjectTypeQueryError = ErrorType<HTTPValidationError>


export function useGetAgentProjectType<TData = Awaited<ReturnType<typeof getAgentProjectType>>, TError = ErrorType<HTTPValidationError>>(
 aptId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentProjectType>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAgentProjectType>>,
          TError,
          Awaited<ReturnType<typeof getAgentProjectType>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAgentProjectType<TData = Awaited<ReturnType<typeof getAgentProjectType>>, TError = ErrorType<HTTPValidationError>>(
 aptId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentProjectType>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAgentProjectType>>,
          TError,
          Awaited<ReturnType<typeof getAgentProjectType>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAgentProjectType<TData = Awaited<ReturnType<typeof getAgentProjectType>>, TError = ErrorType<HTTPValidationError>>(
 aptId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentProjectType>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Agent Project Type
 */

export function useGetAgentProjectType<TData = Awaited<ReturnType<typeof getAgentProjectType>>, TError = ErrorType<HTTPValidationError>>(
 aptId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentProjectType>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAgentProjectTypeQueryOptions(aptId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Delete an agent-project type relationship. Superuser only.

Args:
    apt_id (UUID): The relationship ID.
    current_superuser (User): The current superuser.
    session (SessionDep): The database session.

Raises:
    HTTPException: 404 if the relationship does not exist.
 * @summary Delete Agent Project Type
 */
export const deleteAgentProjectType = (
    aptId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/agent-project-types/${aptId}`, method: 'DELETE', signal
    },
      options);
    }
  


export const getDeleteAgentProjectTypeMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAgentProjectType>>, TError,{aptId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAgentProjectType>>, TError,{aptId: string}, TContext> => {

const mutationKey = ['deleteAgentProjectType'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAgentProjectType>>, {aptId: string}> = (props) => {
          const {aptId} = props ?? {};

          return  deleteAgentProjectType(aptId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAgentProjectTypeMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAgentProjectType>>>
    
    export type DeleteAgentProjectTypeMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Delete Agent Project Type
 */
export const useDeleteAgentProjectType = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAgentProjectType>>, TError,{aptId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAgentProjectType>>,
        TError,
        {aptId: string},
        TContext
      > => {
      return useMutation(getDeleteAgentProjectTypeMutationOptions(options), queryClient);
    }
    