/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Shop Helper
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Create a new agent-project type relationship. Superuser only.

Args:
    apt_in (AgentProjectTypeCreate): The relationship data.
    current_superuser (User): The current superuser.
    session (SessionDep): The database session.

Returns:
    AgentProjectTypePublic: The created relationship.

Raises:
    HTTPException: 404 if agent or project type does not exist.
    HTTPException: 409 if the relationship already exists.
 * @summary Create Agent Project Type
 */
export const AgentProjectTypesCreateAgentProjectTypeBody = zod.object({
  "agent_id": zod.string().uuid(),
  "project_type_id": zod.string().uuid()
}).describe('Schema for creating a new agent-project type relationship.')

/**
 * Get a paginated list of agent-project type relationships. Superuser only.

Args:
    current_superuser (User): The current superuser.
    pagination (PaginationParams): The pagination parameters.
    session (SessionDep): The database session.

Returns:
    PaginatedResponse[AgentProjectTypePublic]: The paginated list of relationships.
 * @summary Get Agent Project Types
 */
export const agentProjectTypesGetAgentProjectTypesQueryOffsetDefault = 0;
export const agentProjectTypesGetAgentProjectTypesQueryOffsetMin = 0;

export const agentProjectTypesGetAgentProjectTypesQueryLimitDefault = 50;
export const agentProjectTypesGetAgentProjectTypesQueryLimitMax = 100;



export const AgentProjectTypesGetAgentProjectTypesQueryParams = zod.object({
  "offset": zod.number().min(agentProjectTypesGetAgentProjectTypesQueryOffsetMin).default(agentProjectTypesGetAgentProjectTypesQueryOffsetDefault),
  "limit": zod.number().min(1).max(agentProjectTypesGetAgentProjectTypesQueryLimitMax).default(agentProjectTypesGetAgentProjectTypesQueryLimitDefault)
})

export const AgentProjectTypesGetAgentProjectTypesResponse = zod.unknown()

/**
 * Get an agent-project type relationship by ID. Superuser only.

Args:
    apt_id (UUID): The relationship ID.
    current_superuser (User): The current superuser.
    session (SessionDep): The database session.

Returns:
    AgentProjectTypePublic: The relationship.

Raises:
    HTTPException: 404 if the relationship does not exist.
 * @summary Get Agent Project Type
 */
export const AgentProjectTypesGetAgentProjectTypeParams = zod.object({
  "apt_id": zod.string().uuid()
})

export const AgentProjectTypesGetAgentProjectTypeResponse = zod.object({
  "id": zod.string().uuid(),
  "agent_id": zod.string().uuid(),
  "project_type_id": zod.string().uuid(),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({}),
  "created_by": zod.string().uuid(),
  "updated_by": zod.string().uuid()
}).describe('Schema for returning agent-project type relationship data to the client.')

/**
 * Delete an agent-project type relationship. Superuser only.

Args:
    apt_id (UUID): The relationship ID.
    current_superuser (User): The current superuser.
    session (SessionDep): The database session.

Raises:
    HTTPException: 404 if the relationship does not exist.
 * @summary Delete Agent Project Type
 */
export const AgentProjectTypesDeleteAgentProjectTypeParams = zod.object({
  "apt_id": zod.string().uuid()
})

