export { default as AvatarShape } from './avatar-shape'
export { default as ComingSoonIllustration } from './coming-soon-illustration'
export { default as ForbiddenIllustration } from './forbidden-illustration'
export { default as PageNotFoundIllustration } from './page-not-found-illustration'
export { default as SeoIllustration } from './seo-illustration'
export { default as ServerErrorIllustration } from './server-error-illustration'
export { default as UploadIllustration } from './upload-illustration'
