/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Shop Helper
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetMyProjectsParams,
  GetOrgProjectsParams,
  HTTPValidationError,
  PaginatedResponseProjectPublic,
  ProjectCreate,
  ProjectPublic,
  ProjectUpdate
} from '.././model';

import { customInstance } from '.././mutator/custom-instance';
import type { ErrorType , BodyType } from '.././mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Create a project in the organization. Admin+ only.

Args:
    org_id (UUID): The organization ID.
    project_in (ProjectCreate): The project data.
    org_admin (tuple[User, OrgUser]): The current user and their org membership.
    session (SessionDep): The database session.

Returns:
    ProjectPublic: The created project.

Raises:
    HTTPException: 400 if org_id mismatch.
    HTTPException: 404 if project type does not exist.
    HTTPException: 409 if project name already exists in org.
 * @summary Create Project
 */
export const createProject = (
    orgId: string,
    projectCreate: BodyType<ProjectCreate>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ProjectPublic>(
      {url: `/orgs/${orgId}/projects`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: projectCreate, signal
    },
      options);
    }
  


export const getCreateProjectMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProject>>, TError,{orgId: string;data: BodyType<ProjectCreate>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createProject>>, TError,{orgId: string;data: BodyType<ProjectCreate>}, TContext> => {

const mutationKey = ['createProject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProject>>, {orgId: string;data: BodyType<ProjectCreate>}> = (props) => {
          const {orgId,data} = props ?? {};

          return  createProject(orgId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateProjectMutationResult = NonNullable<Awaited<ReturnType<typeof createProject>>>
    export type CreateProjectMutationBody = BodyType<ProjectCreate>
    export type CreateProjectMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Project
 */
export const useCreateProject = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProject>>, TError,{orgId: string;data: BodyType<ProjectCreate>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProject>>,
        TError,
        {orgId: string;data: BodyType<ProjectCreate>},
        TContext
      > => {
      return useMutation(getCreateProjectMutationOptions(options), queryClient);
    }
    /**
 * List organization projects. Member access.

Args:
    org_id (UUID): The organization ID.
    org_member (tuple[User, OrgUser]): The current user and their org membership.
    pagination (PaginationParams): The pagination parameters.
    session (SessionDep): The database session.

Returns:
    PaginatedResponse[ProjectPublic]: The paginated list of projects.
 * @summary Get Org Projects
 */
export const getOrgProjects = (
    orgId: string,
    params?: GetOrgProjectsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PaginatedResponseProjectPublic>(
      {url: `/orgs/${orgId}/projects`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetOrgProjectsQueryKey = (orgId: string,
    params?: GetOrgProjectsParams,) => {
    return [
    `/orgs/${orgId}/projects`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetOrgProjectsQueryOptions = <TData = Awaited<ReturnType<typeof getOrgProjects>>, TError = ErrorType<HTTPValidationError>>(orgId: string,
    params?: GetOrgProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrgProjects>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrgProjectsQueryKey(orgId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrgProjects>>> = ({ signal }) => getOrgProjects(orgId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(orgId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrgProjects>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOrgProjectsQueryResult = NonNullable<Awaited<ReturnType<typeof getOrgProjects>>>
export type GetOrgProjectsQueryError = ErrorType<HTTPValidationError>


export function useGetOrgProjects<TData = Awaited<ReturnType<typeof getOrgProjects>>, TError = ErrorType<HTTPValidationError>>(
 orgId: string,
    params: undefined |  GetOrgProjectsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrgProjects>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrgProjects>>,
          TError,
          Awaited<ReturnType<typeof getOrgProjects>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrgProjects<TData = Awaited<ReturnType<typeof getOrgProjects>>, TError = ErrorType<HTTPValidationError>>(
 orgId: string,
    params?: GetOrgProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrgProjects>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrgProjects>>,
          TError,
          Awaited<ReturnType<typeof getOrgProjects>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrgProjects<TData = Awaited<ReturnType<typeof getOrgProjects>>, TError = ErrorType<HTTPValidationError>>(
 orgId: string,
    params?: GetOrgProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrgProjects>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Org Projects
 */

export function useGetOrgProjects<TData = Awaited<ReturnType<typeof getOrgProjects>>, TError = ErrorType<HTTPValidationError>>(
 orgId: string,
    params?: GetOrgProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrgProjects>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOrgProjectsQueryOptions(orgId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get project details. Member access.

Args:
    org_id (UUID): The organization ID.
    project_id (UUID): The project ID.
    org_member (tuple[User, OrgUser]): The current user and their org membership.
    session (SessionDep): The database session.

Returns:
    ProjectPublic: The project.

Raises:
    HTTPException: 404 if the project does not exist or belongs to a different org.
 * @summary Get Project
 */
export const getProject = (
    orgId: string,
    projectId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ProjectPublic>(
      {url: `/orgs/${orgId}/projects/${projectId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetProjectQueryKey = (orgId: string,
    projectId: string,) => {
    return [
    `/orgs/${orgId}/projects/${projectId}`
    ] as const;
    }

    
export const getGetProjectQueryOptions = <TData = Awaited<ReturnType<typeof getProject>>, TError = ErrorType<HTTPValidationError>>(orgId: string,
    projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProjectQueryKey(orgId,projectId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProject>>> = ({ signal }) => getProject(orgId,projectId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(orgId && projectId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProjectQueryResult = NonNullable<Awaited<ReturnType<typeof getProject>>>
export type GetProjectQueryError = ErrorType<HTTPValidationError>


export function useGetProject<TData = Awaited<ReturnType<typeof getProject>>, TError = ErrorType<HTTPValidationError>>(
 orgId: string,
    projectId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProject>>,
          TError,
          Awaited<ReturnType<typeof getProject>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProject<TData = Awaited<ReturnType<typeof getProject>>, TError = ErrorType<HTTPValidationError>>(
 orgId: string,
    projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProject>>,
          TError,
          Awaited<ReturnType<typeof getProject>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProject<TData = Awaited<ReturnType<typeof getProject>>, TError = ErrorType<HTTPValidationError>>(
 orgId: string,
    projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Project
 */

export function useGetProject<TData = Awaited<ReturnType<typeof getProject>>, TError = ErrorType<HTTPValidationError>>(
 orgId: string,
    projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProjectQueryOptions(orgId,projectId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update project. Admin+ only.

Args:
    org_id (UUID): The organization ID.
    project_id (UUID): The project ID.
    project_in (ProjectUpdate): The update data.
    org_admin (tuple[User, OrgUser]): The current user and their org membership.
    session (SessionDep): The database session.

Returns:
    ProjectPublic: The updated project.

Raises:
    HTTPException: 404 if the project does not exist or belongs to a different org, or project type not found.
    HTTPException: 409 if project name already exists in org.
 * @summary Update Project
 */
export const updateProject = (
    orgId: string,
    projectId: string,
    projectUpdate: BodyType<ProjectUpdate>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ProjectPublic>(
      {url: `/orgs/${orgId}/projects/${projectId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: projectUpdate, signal
    },
      options);
    }
  


export const getUpdateProjectMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProject>>, TError,{orgId: string;projectId: string;data: BodyType<ProjectUpdate>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateProject>>, TError,{orgId: string;projectId: string;data: BodyType<ProjectUpdate>}, TContext> => {

const mutationKey = ['updateProject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProject>>, {orgId: string;projectId: string;data: BodyType<ProjectUpdate>}> = (props) => {
          const {orgId,projectId,data} = props ?? {};

          return  updateProject(orgId,projectId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateProjectMutationResult = NonNullable<Awaited<ReturnType<typeof updateProject>>>
    export type UpdateProjectMutationBody = BodyType<ProjectUpdate>
    export type UpdateProjectMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Project
 */
export const useUpdateProject = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProject>>, TError,{orgId: string;projectId: string;data: BodyType<ProjectUpdate>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProject>>,
        TError,
        {orgId: string;projectId: string;data: BodyType<ProjectUpdate>},
        TContext
      > => {
      return useMutation(getUpdateProjectMutationOptions(options), queryClient);
    }
    /**
 * Delete project. Admin+ only.

Args:
    org_id (UUID): The organization ID.
    project_id (UUID): The project ID.
    org_admin (tuple[User, OrgUser]): The current user and their org membership.
    session (SessionDep): The database session.

Raises:
    HTTPException: 404 if the project does not exist or belongs to a different org.
 * @summary Delete Project
 */
export const deleteProject = (
    orgId: string,
    projectId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/orgs/${orgId}/projects/${projectId}`, method: 'DELETE', signal
    },
      options);
    }
  


export const getDeleteProjectMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProject>>, TError,{orgId: string;projectId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteProject>>, TError,{orgId: string;projectId: string}, TContext> => {

const mutationKey = ['deleteProject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProject>>, {orgId: string;projectId: string}> = (props) => {
          const {orgId,projectId} = props ?? {};

          return  deleteProject(orgId,projectId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteProjectMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProject>>>
    
    export type DeleteProjectMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Delete Project
 */
export const useDeleteProject = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProject>>, TError,{orgId: string;projectId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProject>>,
        TError,
        {orgId: string;projectId: string},
        TContext
      > => {
      return useMutation(getDeleteProjectMutationOptions(options), queryClient);
    }
    /**
 * Get all projects the current user has access to across all organizations.

Args:
    current_user (User): The current authenticated user.
    pagination (PaginationParams): The pagination parameters.
    session (SessionDep): The database session.

Returns:
    PaginatedResponse[ProjectPublic]: The paginated list of projects.
 * @summary Get My Projects
 */
export const getMyProjects = (
    params?: GetMyProjectsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PaginatedResponseProjectPublic>(
      {url: `/projects/`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetMyProjectsQueryKey = (params?: GetMyProjectsParams,) => {
    return [
    `/projects/`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetMyProjectsQueryOptions = <TData = Awaited<ReturnType<typeof getMyProjects>>, TError = ErrorType<HTTPValidationError>>(params?: GetMyProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyProjects>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyProjectsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyProjects>>> = ({ signal }) => getMyProjects(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyProjects>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyProjectsQueryResult = NonNullable<Awaited<ReturnType<typeof getMyProjects>>>
export type GetMyProjectsQueryError = ErrorType<HTTPValidationError>


export function useGetMyProjects<TData = Awaited<ReturnType<typeof getMyProjects>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  GetMyProjectsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyProjects>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyProjects>>,
          TError,
          Awaited<ReturnType<typeof getMyProjects>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyProjects<TData = Awaited<ReturnType<typeof getMyProjects>>, TError = ErrorType<HTTPValidationError>>(
 params?: GetMyProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyProjects>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyProjects>>,
          TError,
          Awaited<ReturnType<typeof getMyProjects>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyProjects<TData = Awaited<ReturnType<typeof getMyProjects>>, TError = ErrorType<HTTPValidationError>>(
 params?: GetMyProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyProjects>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get My Projects
 */

export function useGetMyProjects<TData = Awaited<ReturnType<typeof getMyProjects>>, TError = ErrorType<HTTPValidationError>>(
 params?: GetMyProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyProjects>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyProjectsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




