/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Shop Helper
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Create a project in the organization. Admin+ only.

Args:
    org_id (UUID): The organization ID.
    project_in (ProjectCreate): The project data.
    org_admin (tuple[User, OrgUser]): The current user and their org membership.
    session (SessionDep): The database session.

Returns:
    ProjectPublic: The created project.

Raises:
    HTTPException: 400 if org_id mismatch.
    HTTPException: 404 if project type does not exist.
    HTTPException: 409 if project name already exists in org.
 * @summary Create Project
 */
export const ProjectsCreateProjectParams = zod.object({
  "org_id": zod.string().uuid()
})

export const projectsCreateProjectBodyNameMax = 255;



export const ProjectsCreateProjectBody = zod.object({
  "org_id": zod.string().uuid(),
  "name": zod.string().min(1).max(projectsCreateProjectBodyNameMax),
  "project_type_id": zod.string().uuid()
}).describe('Schema for creating a new project.')

/**
 * List organization projects. Member access.

Args:
    org_id (UUID): The organization ID.
    org_member (tuple[User, OrgUser]): The current user and their org membership.
    pagination (PaginationParams): The pagination parameters.
    session (SessionDep): The database session.

Returns:
    PaginatedResponse[ProjectPublic]: The paginated list of projects.
 * @summary Get Org Projects
 */
export const ProjectsGetOrgProjectsParams = zod.object({
  "org_id": zod.string().uuid()
})

export const projectsGetOrgProjectsQueryOffsetDefault = 0;
export const projectsGetOrgProjectsQueryOffsetMin = 0;

export const projectsGetOrgProjectsQueryLimitDefault = 50;
export const projectsGetOrgProjectsQueryLimitMax = 100;



export const ProjectsGetOrgProjectsQueryParams = zod.object({
  "offset": zod.number().min(projectsGetOrgProjectsQueryOffsetMin).default(projectsGetOrgProjectsQueryOffsetDefault),
  "limit": zod.number().min(1).max(projectsGetOrgProjectsQueryLimitMax).default(projectsGetOrgProjectsQueryLimitDefault)
})

export const ProjectsGetOrgProjectsResponse = zod.unknown()

/**
 * Get project details. Member access.

Args:
    org_id (UUID): The organization ID.
    project_id (UUID): The project ID.
    org_member (tuple[User, OrgUser]): The current user and their org membership.
    session (SessionDep): The database session.

Returns:
    ProjectPublic: The project.

Raises:
    HTTPException: 404 if the project does not exist or belongs to a different org.
 * @summary Get Project
 */
export const ProjectsGetProjectParams = zod.object({
  "org_id": zod.string().uuid(),
  "project_id": zod.string().uuid()
})

export const ProjectsGetProjectResponse = zod.object({
  "id": zod.string().uuid(),
  "org_id": zod.string().uuid(),
  "name": zod.string(),
  "project_type_id": zod.string().uuid(),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({}),
  "created_by": zod.string().uuid(),
  "updated_by": zod.string().uuid()
}).describe('Schema for returning project data to the client.')

/**
 * Update project. Admin+ only.

Args:
    org_id (UUID): The organization ID.
    project_id (UUID): The project ID.
    project_in (ProjectUpdate): The update data.
    org_admin (tuple[User, OrgUser]): The current user and their org membership.
    session (SessionDep): The database session.

Returns:
    ProjectPublic: The updated project.

Raises:
    HTTPException: 404 if the project does not exist or belongs to a different org, or project type not found.
    HTTPException: 409 if project name already exists in org.
 * @summary Update Project
 */
export const ProjectsUpdateProjectParams = zod.object({
  "org_id": zod.string().uuid(),
  "project_id": zod.string().uuid()
})

export const projectsUpdateProjectBodyNameOneMax = 255;



export const ProjectsUpdateProjectBody = zod.object({
  "name": zod.union([zod.string().min(1).max(projectsUpdateProjectBodyNameOneMax),zod.null()]).optional(),
  "project_type_id": zod.union([zod.string().uuid(),zod.null()]).optional()
}).describe('Schema for updating a project.')

export const ProjectsUpdateProjectResponse = zod.object({
  "id": zod.string().uuid(),
  "org_id": zod.string().uuid(),
  "name": zod.string(),
  "project_type_id": zod.string().uuid(),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({}),
  "created_by": zod.string().uuid(),
  "updated_by": zod.string().uuid()
}).describe('Schema for returning project data to the client.')

/**
 * Delete project. Admin+ only.

Args:
    org_id (UUID): The organization ID.
    project_id (UUID): The project ID.
    org_admin (tuple[User, OrgUser]): The current user and their org membership.
    session (SessionDep): The database session.

Raises:
    HTTPException: 404 if the project does not exist or belongs to a different org.
 * @summary Delete Project
 */
export const ProjectsDeleteProjectParams = zod.object({
  "org_id": zod.string().uuid(),
  "project_id": zod.string().uuid()
})

