/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * AI Shop Helper
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Register a new user.

Args:
    user_in (UserCreate): The user data.
    session (AsyncSession): The database session.

Returns:
    UserPublic: The created user.

Raises:
    HTTPException: 409 if the email is already registered.
 * @summary Register
 */
export const AuthRegisterBody = zod.object({
  "email": zod.string().email(),
  "name": zod.string(),
  "password": zod.string()
}).describe('Schema for creating a new user.')

/**
 * Login a user and return an access token.

Args:
    response (Response): The HTTP response.
    form_data (OAuth2PasswordRequestForm): The login form data containing username and password.
    session (AsyncSession): The database session.

Returns:
    Token: The access token.

Raises:
    HTTPException: 401 if the credentials are invalid.
 * @summary Login
 */
export const authLoginResponseTokenTypeDefault = `bearer`;

export const AuthLoginResponse = zod.object({
  "access_token": zod.string(),
  "token_type": zod.string().default(authLoginResponseTokenTypeDefault)
}).describe('Schema for the access token response.')

/**
 * Refresh an access token using a refresh token cookie.

Args:
    response (Response): The HTTP response.
    session (AsyncSession): The database session.
    refresh_token (str): The refresh token from the cookie.

Returns:
    Token: The new access token.

Raises:
    HTTPException: 401 if the refresh token is invalid or expired.
 * @summary Refresh
 */
export const authRefreshResponseTokenTypeDefault = `bearer`;

export const AuthRefreshResponse = zod.object({
  "access_token": zod.string(),
  "token_type": zod.string().default(authRefreshResponseTokenTypeDefault)
}).describe('Schema for the access token response.')

