/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Shop Helper
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Create a new project type. Superuser only.

Args:
    project_type_in (ProjectTypeCreate): The project type data.
    current_superuser (User): The current superuser.
    session (SessionDep): The database session.

Returns:
    ProjectTypePublic: The created project type.

Raises:
    HTTPException: 409 if the project type name is already registered.
 * @summary Create Project Type
 */
export const projectTypesCreateProjectTypeBodyNameMax = 255;



export const ProjectTypesCreateProjectTypeBody = zod.object({
  "name": zod.string().min(1).max(projectTypesCreateProjectTypeBodyNameMax)
}).describe('Schema for creating a new project type.')

/**
 * Get a paginated list of project types. Superuser only.

Args:
    current_superuser (User): The current superuser.
    pagination (PaginationParams): The pagination parameters.
    session (SessionDep): The database session.

Returns:
    PaginatedResponse[ProjectTypePublic]: The paginated list of project types.
 * @summary Get Project Types
 */
export const projectTypesGetProjectTypesQueryOffsetDefault = 0;
export const projectTypesGetProjectTypesQueryOffsetMin = 0;

export const projectTypesGetProjectTypesQueryLimitDefault = 50;
export const projectTypesGetProjectTypesQueryLimitMax = 100;



export const ProjectTypesGetProjectTypesQueryParams = zod.object({
  "offset": zod.number().min(projectTypesGetProjectTypesQueryOffsetMin).default(projectTypesGetProjectTypesQueryOffsetDefault),
  "limit": zod.number().min(1).max(projectTypesGetProjectTypesQueryLimitMax).default(projectTypesGetProjectTypesQueryLimitDefault)
})

export const ProjectTypesGetProjectTypesResponse = zod.unknown()

/**
 * Get a project type by ID. Superuser only.

Args:
    project_type_id (UUID): The project type ID.
    current_superuser (User): The current superuser.
    session (SessionDep): The database session.

Returns:
    ProjectTypePublic: The project type.

Raises:
    HTTPException: 404 if the project type does not exist.
 * @summary Get Project Type
 */
export const ProjectTypesGetProjectTypeParams = zod.object({
  "project_type_id": zod.string().uuid()
})

export const ProjectTypesGetProjectTypeResponse = zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({}),
  "created_by": zod.string().uuid(),
  "updated_by": zod.string().uuid()
}).describe('Schema for returning project type data to the client.')

/**
 * Update a project type. Superuser only.

Args:
    project_type_id (UUID): The project type ID.
    project_type_in (ProjectTypeUpdate): The update data.
    current_superuser (User): The current superuser.
    session (SessionDep): The database session.

Returns:
    ProjectTypePublic: The updated project type.

Raises:
    HTTPException: 404 if the project type does not exist.
    HTTPException: 409 if the project type name is already registered.
 * @summary Update Project Type
 */
export const ProjectTypesUpdateProjectTypeParams = zod.object({
  "project_type_id": zod.string().uuid()
})

export const projectTypesUpdateProjectTypeBodyNameOneMax = 255;



export const ProjectTypesUpdateProjectTypeBody = zod.object({
  "name": zod.union([zod.string().min(1).max(projectTypesUpdateProjectTypeBodyNameOneMax),zod.null()]).optional()
}).describe('Schema for updating a project type.')

export const ProjectTypesUpdateProjectTypeResponse = zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({}),
  "created_by": zod.string().uuid(),
  "updated_by": zod.string().uuid()
}).describe('Schema for returning project type data to the client.')

/**
 * Delete a project type. Superuser only.

Args:
    project_type_id (UUID): The project type ID.
    current_superuser (User): The current superuser.
    session (SessionDep): The database session.

Raises:
    HTTPException: 404 if the project type does not exist.
 * @summary Delete Project Type
 */
export const ProjectTypesDeleteProjectTypeParams = zod.object({
  "project_type_id": zod.string().uuid()
})

