/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Shop Helper
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetProjectTypesParams,
  HTTPValidationError,
  PaginatedResponseProjectTypePublic,
  ProjectTypeCreate,
  ProjectTypePublic,
  ProjectTypeUpdate
} from '.././model';

import { customInstance } from '.././mutator/custom-instance';
import type { ErrorType , BodyType } from '.././mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Create a new project type. Superuser only.

Args:
    project_type_in (ProjectTypeCreate): The project type data.
    current_superuser (User): The current superuser.
    session (SessionDep): The database session.

Returns:
    ProjectTypePublic: The created project type.

Raises:
    HTTPException: 409 if the project type name is already registered.
 * @summary Create Project Type
 */
export const createProjectType = (
    projectTypeCreate: BodyType<ProjectTypeCreate>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ProjectTypePublic>(
      {url: `/project-types/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: projectTypeCreate, signal
    },
      options);
    }
  


export const getCreateProjectTypeMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProjectType>>, TError,{data: BodyType<ProjectTypeCreate>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createProjectType>>, TError,{data: BodyType<ProjectTypeCreate>}, TContext> => {

const mutationKey = ['createProjectType'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProjectType>>, {data: BodyType<ProjectTypeCreate>}> = (props) => {
          const {data} = props ?? {};

          return  createProjectType(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateProjectTypeMutationResult = NonNullable<Awaited<ReturnType<typeof createProjectType>>>
    export type CreateProjectTypeMutationBody = BodyType<ProjectTypeCreate>
    export type CreateProjectTypeMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Project Type
 */
export const useCreateProjectType = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProjectType>>, TError,{data: BodyType<ProjectTypeCreate>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProjectType>>,
        TError,
        {data: BodyType<ProjectTypeCreate>},
        TContext
      > => {
      return useMutation(getCreateProjectTypeMutationOptions(options), queryClient);
    }
    /**
 * Get a paginated list of project types. Superuser only.

Args:
    current_superuser (User): The current superuser.
    pagination (PaginationParams): The pagination parameters.
    session (SessionDep): The database session.

Returns:
    PaginatedResponse[ProjectTypePublic]: The paginated list of project types.
 * @summary Get Project Types
 */
export const getProjectTypes = (
    params?: GetProjectTypesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PaginatedResponseProjectTypePublic>(
      {url: `/project-types/`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetProjectTypesQueryKey = (params?: GetProjectTypesParams,) => {
    return [
    `/project-types/`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetProjectTypesQueryOptions = <TData = Awaited<ReturnType<typeof getProjectTypes>>, TError = ErrorType<HTTPValidationError>>(params?: GetProjectTypesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectTypes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProjectTypesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProjectTypes>>> = ({ signal }) => getProjectTypes(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProjectTypes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProjectTypesQueryResult = NonNullable<Awaited<ReturnType<typeof getProjectTypes>>>
export type GetProjectTypesQueryError = ErrorType<HTTPValidationError>


export function useGetProjectTypes<TData = Awaited<ReturnType<typeof getProjectTypes>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  GetProjectTypesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectTypes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectTypes>>,
          TError,
          Awaited<ReturnType<typeof getProjectTypes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProjectTypes<TData = Awaited<ReturnType<typeof getProjectTypes>>, TError = ErrorType<HTTPValidationError>>(
 params?: GetProjectTypesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectTypes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectTypes>>,
          TError,
          Awaited<ReturnType<typeof getProjectTypes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProjectTypes<TData = Awaited<ReturnType<typeof getProjectTypes>>, TError = ErrorType<HTTPValidationError>>(
 params?: GetProjectTypesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectTypes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Project Types
 */

export function useGetProjectTypes<TData = Awaited<ReturnType<typeof getProjectTypes>>, TError = ErrorType<HTTPValidationError>>(
 params?: GetProjectTypesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectTypes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProjectTypesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get a project type by ID. Superuser only.

Args:
    project_type_id (UUID): The project type ID.
    current_superuser (User): The current superuser.
    session (SessionDep): The database session.

Returns:
    ProjectTypePublic: The project type.

Raises:
    HTTPException: 404 if the project type does not exist.
 * @summary Get Project Type
 */
export const getProjectType = (
    projectTypeId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ProjectTypePublic>(
      {url: `/project-types/${projectTypeId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetProjectTypeQueryKey = (projectTypeId: string,) => {
    return [
    `/project-types/${projectTypeId}`
    ] as const;
    }

    
export const getGetProjectTypeQueryOptions = <TData = Awaited<ReturnType<typeof getProjectType>>, TError = ErrorType<HTTPValidationError>>(projectTypeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectType>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProjectTypeQueryKey(projectTypeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProjectType>>> = ({ signal }) => getProjectType(projectTypeId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(projectTypeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProjectType>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProjectTypeQueryResult = NonNullable<Awaited<ReturnType<typeof getProjectType>>>
export type GetProjectTypeQueryError = ErrorType<HTTPValidationError>


export function useGetProjectType<TData = Awaited<ReturnType<typeof getProjectType>>, TError = ErrorType<HTTPValidationError>>(
 projectTypeId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectType>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectType>>,
          TError,
          Awaited<ReturnType<typeof getProjectType>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProjectType<TData = Awaited<ReturnType<typeof getProjectType>>, TError = ErrorType<HTTPValidationError>>(
 projectTypeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectType>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectType>>,
          TError,
          Awaited<ReturnType<typeof getProjectType>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProjectType<TData = Awaited<ReturnType<typeof getProjectType>>, TError = ErrorType<HTTPValidationError>>(
 projectTypeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectType>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Project Type
 */

export function useGetProjectType<TData = Awaited<ReturnType<typeof getProjectType>>, TError = ErrorType<HTTPValidationError>>(
 projectTypeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectType>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProjectTypeQueryOptions(projectTypeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update a project type. Superuser only.

Args:
    project_type_id (UUID): The project type ID.
    project_type_in (ProjectTypeUpdate): The update data.
    current_superuser (User): The current superuser.
    session (SessionDep): The database session.

Returns:
    ProjectTypePublic: The updated project type.

Raises:
    HTTPException: 404 if the project type does not exist.
    HTTPException: 409 if the project type name is already registered.
 * @summary Update Project Type
 */
export const updateProjectType = (
    projectTypeId: string,
    projectTypeUpdate: BodyType<ProjectTypeUpdate>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ProjectTypePublic>(
      {url: `/project-types/${projectTypeId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: projectTypeUpdate, signal
    },
      options);
    }
  


export const getUpdateProjectTypeMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProjectType>>, TError,{projectTypeId: string;data: BodyType<ProjectTypeUpdate>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateProjectType>>, TError,{projectTypeId: string;data: BodyType<ProjectTypeUpdate>}, TContext> => {

const mutationKey = ['updateProjectType'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProjectType>>, {projectTypeId: string;data: BodyType<ProjectTypeUpdate>}> = (props) => {
          const {projectTypeId,data} = props ?? {};

          return  updateProjectType(projectTypeId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateProjectTypeMutationResult = NonNullable<Awaited<ReturnType<typeof updateProjectType>>>
    export type UpdateProjectTypeMutationBody = BodyType<ProjectTypeUpdate>
    export type UpdateProjectTypeMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Project Type
 */
export const useUpdateProjectType = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProjectType>>, TError,{projectTypeId: string;data: BodyType<ProjectTypeUpdate>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProjectType>>,
        TError,
        {projectTypeId: string;data: BodyType<ProjectTypeUpdate>},
        TContext
      > => {
      return useMutation(getUpdateProjectTypeMutationOptions(options), queryClient);
    }
    /**
 * Delete a project type. Superuser only.

Args:
    project_type_id (UUID): The project type ID.
    current_superuser (User): The current superuser.
    session (SessionDep): The database session.

Raises:
    HTTPException: 404 if the project type does not exist.
 * @summary Delete Project Type
 */
export const deleteProjectType = (
    projectTypeId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/project-types/${projectTypeId}`, method: 'DELETE', signal
    },
      options);
    }
  


export const getDeleteProjectTypeMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProjectType>>, TError,{projectTypeId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteProjectType>>, TError,{projectTypeId: string}, TContext> => {

const mutationKey = ['deleteProjectType'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProjectType>>, {projectTypeId: string}> = (props) => {
          const {projectTypeId} = props ?? {};

          return  deleteProjectType(projectTypeId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteProjectTypeMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProjectType>>>
    
    export type DeleteProjectTypeMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Delete Project Type
 */
export const useDeleteProjectType = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProjectType>>, TError,{projectTypeId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProjectType>>,
        TError,
        {projectTypeId: string},
        TContext
      > => {
      return useMutation(getDeleteProjectTypeMutationOptions(options), queryClient);
    }
    