// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { healthHealthGet, type Options, readItemItemsItemIdGet, readRootGet } from '../sdk.gen';
import type { HealthHealthGetData, HealthHealthGetResponse, ReadItemItemsItemIdGetData, ReadItemItemsItemIdGetError, ReadItemItemsItemIdGetResponse, ReadRootGetData, ReadRootGetResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const readRootGetQueryKey = (options?: Options<ReadRootGetData>) => createQueryKey('readRootGet', options);

/**
 * Read Root
 */
export const readRootGetOptions = (options?: Options<ReadRootGetData>) => queryOptions<ReadRootGetResponse, AxiosError<DefaultError>, ReadRootGetResponse, ReturnType<typeof readRootGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readRootGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readRootGetQueryKey(options)
});

export const healthHealthGetQueryKey = (options?: Options<HealthHealthGetData>) => createQueryKey('healthHealthGet', options);

/**
 * Health
 */
export const healthHealthGetOptions = (options?: Options<HealthHealthGetData>) => queryOptions<HealthHealthGetResponse, AxiosError<DefaultError>, HealthHealthGetResponse, ReturnType<typeof healthHealthGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await healthHealthGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthHealthGetQueryKey(options)
});

export const readItemItemsItemIdGetQueryKey = (options: Options<ReadItemItemsItemIdGetData>) => createQueryKey('readItemItemsItemIdGet', options);

/**
 * Read Item
 */
export const readItemItemsItemIdGetOptions = (options: Options<ReadItemItemsItemIdGetData>) => queryOptions<ReadItemItemsItemIdGetResponse, AxiosError<ReadItemItemsItemIdGetError>, ReadItemItemsItemIdGetResponse, ReturnType<typeof readItemItemsItemIdGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readItemItemsItemIdGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readItemItemsItemIdGetQueryKey(options)
});
