/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Shop Helper
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Create a new role. Superuser only.

Args:
    role_in (RoleCreate): The role data.
    current_superuser (User): The current superuser.
    session (SessionDep): The database session.

Returns:
    RolePublic: The created role.

Raises:
    HTTPException: 409 if the role name is already registered.
 * @summary Create Role
 */
export const rolesCreateRoleBodyNameMax = 255;

export const rolesCreateRoleBodyAccessLevelMin = 0;
export const rolesCreateRoleBodyAccessLevelMax = 100;



export const RolesCreateRoleBody = zod.object({
  "name": zod.string().min(1).max(rolesCreateRoleBodyNameMax),
  "description": zod.union([zod.string(),zod.null()]).optional(),
  "access_level": zod.number().min(rolesCreateRoleBodyAccessLevelMin).max(rolesCreateRoleBodyAccessLevelMax)
}).describe('Schema for creating a new role.')

/**
 * Get a paginated list of roles.

Args:
    current_user (User): The current authenticated user.
    pagination (PaginationParams): The pagination parameters.
    session (SessionDep): The database session.

Returns:
    PaginatedResponse[RolePublic]: The paginated list of roles.
 * @summary Get Roles
 */
export const rolesGetRolesQueryOffsetDefault = 0;
export const rolesGetRolesQueryOffsetMin = 0;

export const rolesGetRolesQueryLimitDefault = 50;
export const rolesGetRolesQueryLimitMax = 100;



export const RolesGetRolesQueryParams = zod.object({
  "offset": zod.number().min(rolesGetRolesQueryOffsetMin).default(rolesGetRolesQueryOffsetDefault),
  "limit": zod.number().min(1).max(rolesGetRolesQueryLimitMax).default(rolesGetRolesQueryLimitDefault)
})

export const RolesGetRolesResponse = zod.unknown()

/**
 * Get a role by ID.

Args:
    role_id (UUID): The role ID.
    current_user (User): The current authenticated user.
    session (SessionDep): The database session.

Returns:
    RolePublic: The role.

Raises:
    HTTPException: 404 if the role does not exist.
 * @summary Get Role
 */
export const RolesGetRoleParams = zod.object({
  "role_id": zod.string().uuid()
})

export const RolesGetRoleResponse = zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]),
  "access_level": zod.number(),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({}),
  "created_by": zod.string().uuid(),
  "updated_by": zod.string().uuid()
}).describe('Schema for returning role data to the client.')

/**
 * Update a role. Superuser only.

Args:
    role_id (UUID): The role ID.
    role_in (RoleUpdate): The update data.
    current_superuser (User): The current superuser.
    session (SessionDep): The database session.

Returns:
    RolePublic: The updated role.

Raises:
    HTTPException: 404 if the role does not exist.
    HTTPException: 409 if the role name is already registered.
 * @summary Update Role
 */
export const RolesUpdateRoleParams = zod.object({
  "role_id": zod.string().uuid()
})

export const rolesUpdateRoleBodyNameOneMax = 255;

export const rolesUpdateRoleBodyAccessLevelOneMin = 0;
export const rolesUpdateRoleBodyAccessLevelOneMax = 100;



export const RolesUpdateRoleBody = zod.object({
  "name": zod.union([zod.string().min(1).max(rolesUpdateRoleBodyNameOneMax),zod.null()]).optional(),
  "description": zod.union([zod.string(),zod.null()]).optional(),
  "access_level": zod.union([zod.number().min(rolesUpdateRoleBodyAccessLevelOneMin).max(rolesUpdateRoleBodyAccessLevelOneMax),zod.null()]).optional()
}).describe('Schema for updating a role.')

export const RolesUpdateRoleResponse = zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]),
  "access_level": zod.number(),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({}),
  "created_by": zod.string().uuid(),
  "updated_by": zod.string().uuid()
}).describe('Schema for returning role data to the client.')

/**
 * Delete a role. Superuser only.

Args:
    role_id (UUID): The role ID.
    current_superuser (User): The current superuser.
    session (SessionDep): The database session.

Raises:
    HTTPException: 404 if the role does not exist.
 * @summary Delete Role
 */
export const RolesDeleteRoleParams = zod.object({
  "role_id": zod.string().uuid()
})

