/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Shop Helper
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for creating a new agent-project type relationship.
 */
export interface AgentProjectTypeCreate {
  agent_id: string;
  project_type_id: string;
}
