/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Shop Helper
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for returning agent-project type relationship data to the client.
 */
export interface AgentProjectTypePublic {
  id: string;
  agent_id: string;
  project_type_id: string;
  created_at: string;
  updated_at: string;
  created_by: string;
  updated_by: string;
}
