/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Shop Helper
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for updating a member's role.
 */
export interface OrgUserUpdate {
  role_id: string;
}
