/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Shop Helper
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for adding a member to an organization.
 */
export interface OrgUserCreate {
  user_id: string;
  org_id: string;
  role_id: string;
}
