/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Shop Helper
 * OpenAPI spec version: 0.1.0
 */

export interface PaginatedResponseAgentPublic {
  items: unknown[];
  total: number;
  offset: number;
  limit: number;
}
