/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Shop Helper
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for creating a new project.
 */
export interface ProjectCreate {
  org_id: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  project_type_id: string;
}
