/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Shop Helper
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for updating a role.
 */
export interface RoleUpdate {
  name?: string | null;
  description?: string | null;
  access_level?: number | null;
}
