/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Shop Helper
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for the access token response.
 */
export interface Token {
  access_token: string;
  token_type?: string;
}
