/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * AI Shop Helper
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for creating a new user.
 */
export interface UserCreate {
  email: string;
  name: string;
  /**
   * @minLength 8
   * @maxLength 128
   */
  password: string;
}
