/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Shop Helper
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for updating the current user's own profile.
 */
export interface UserUpdate {
  email?: string | null;
  name?: string | null;
  password?: string | null;
}
