/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Shop Helper
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Create a new agent. Superuser only.

Args:
    agent_in (AgentCreate): The agent data.
    current_superuser (User): The current superuser.
    session (SessionDep): The database session.

Returns:
    AgentPublic: The created agent.

Raises:
    HTTPException: 409 if the agent name is already registered.
 * @summary Create Agent
 */
export const agentsCreateAgentBodyNameMax = 255;



export const AgentsCreateAgentBody = zod.object({
  "name": zod.string().min(1).max(agentsCreateAgentBodyNameMax),
  "description": zod.union([zod.string(),zod.null()]).optional()
}).describe('Schema for creating a new agent.')

/**
 * Get a paginated list of agents. Superuser only.

Args:
    current_superuser (User): The current superuser.
    pagination (PaginationParams): The pagination parameters.
    session (SessionDep): The database session.

Returns:
    PaginatedResponse[AgentPublic]: The paginated list of agents.
 * @summary Get Agents
 */
export const agentsGetAgentsQueryOffsetDefault = 0;
export const agentsGetAgentsQueryOffsetMin = 0;

export const agentsGetAgentsQueryLimitDefault = 50;
export const agentsGetAgentsQueryLimitMax = 100;



export const AgentsGetAgentsQueryParams = zod.object({
  "offset": zod.number().min(agentsGetAgentsQueryOffsetMin).default(agentsGetAgentsQueryOffsetDefault),
  "limit": zod.number().min(1).max(agentsGetAgentsQueryLimitMax).default(agentsGetAgentsQueryLimitDefault)
})

export const AgentsGetAgentsResponse = zod.unknown()

/**
 * Get an agent by ID. Superuser only.

Args:
    agent_id (UUID): The agent ID.
    current_superuser (User): The current superuser.
    session (SessionDep): The database session.

Returns:
    AgentPublic: The agent.

Raises:
    HTTPException: 404 if the agent does not exist.
 * @summary Get Agent
 */
export const AgentsGetAgentParams = zod.object({
  "agent_id": zod.string().uuid()
})

export const AgentsGetAgentResponse = zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({}),
  "created_by": zod.string().uuid(),
  "updated_by": zod.string().uuid()
}).describe('Schema for returning agent data to the client.')

/**
 * Update an agent. Superuser only.

Args:
    agent_id (UUID): The agent ID.
    agent_in (AgentUpdate): The update data.
    current_superuser (User): The current superuser.
    session (SessionDep): The database session.

Returns:
    AgentPublic: The updated agent.

Raises:
    HTTPException: 404 if the agent does not exist.
    HTTPException: 409 if the agent name is already registered.
 * @summary Update Agent
 */
export const AgentsUpdateAgentParams = zod.object({
  "agent_id": zod.string().uuid()
})

export const agentsUpdateAgentBodyNameOneMax = 255;



export const AgentsUpdateAgentBody = zod.object({
  "name": zod.union([zod.string().min(1).max(agentsUpdateAgentBodyNameOneMax),zod.null()]).optional(),
  "description": zod.union([zod.string(),zod.null()]).optional()
}).describe('Schema for updating an agent.')

export const AgentsUpdateAgentResponse = zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({}),
  "created_by": zod.string().uuid(),
  "updated_by": zod.string().uuid()
}).describe('Schema for returning agent data to the client.')

/**
 * Delete an agent. Superuser only.

Args:
    agent_id (UUID): The agent ID.
    current_superuser (User): The current superuser.
    session (SessionDep): The database session.

Raises:
    HTTPException: 404 if the agent does not exist.
 * @summary Delete Agent
 */
export const AgentsDeleteAgentParams = zod.object({
  "agent_id": zod.string().uuid()
})

