/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Shop Helper
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AgentCreate,
  AgentPublic,
  AgentUpdate,
  GetAgentsParams,
  HTTPValidationError,
  PaginatedResponseAgentPublic
} from '.././model';

import { customInstance } from '.././mutator/custom-instance';
import type { ErrorType , BodyType } from '.././mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Create a new agent. Superuser only.

Args:
    agent_in (AgentCreate): The agent data.
    current_superuser (User): The current superuser.
    session (SessionDep): The database session.

Returns:
    AgentPublic: The created agent.

Raises:
    HTTPException: 409 if the agent name is already registered.
 * @summary Create Agent
 */
export const createAgent = (
    agentCreate: BodyType<AgentCreate>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AgentPublic>(
      {url: `/agents/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: agentCreate, signal
    },
      options);
    }
  


export const getCreateAgentMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAgent>>, TError,{data: BodyType<AgentCreate>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createAgent>>, TError,{data: BodyType<AgentCreate>}, TContext> => {

const mutationKey = ['createAgent'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createAgent>>, {data: BodyType<AgentCreate>}> = (props) => {
          const {data} = props ?? {};

          return  createAgent(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateAgentMutationResult = NonNullable<Awaited<ReturnType<typeof createAgent>>>
    export type CreateAgentMutationBody = BodyType<AgentCreate>
    export type CreateAgentMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Agent
 */
export const useCreateAgent = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAgent>>, TError,{data: BodyType<AgentCreate>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createAgent>>,
        TError,
        {data: BodyType<AgentCreate>},
        TContext
      > => {
      return useMutation(getCreateAgentMutationOptions(options), queryClient);
    }
    /**
 * Get a paginated list of agents. Superuser only.

Args:
    current_superuser (User): The current superuser.
    pagination (PaginationParams): The pagination parameters.
    session (SessionDep): The database session.

Returns:
    PaginatedResponse[AgentPublic]: The paginated list of agents.
 * @summary Get Agents
 */
export const getAgents = (
    params?: GetAgentsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PaginatedResponseAgentPublic>(
      {url: `/agents/`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAgentsQueryKey = (params?: GetAgentsParams,) => {
    return [
    `/agents/`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetAgentsQueryOptions = <TData = Awaited<ReturnType<typeof getAgents>>, TError = ErrorType<HTTPValidationError>>(params?: GetAgentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAgentsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAgents>>> = ({ signal }) => getAgents(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAgents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAgentsQueryResult = NonNullable<Awaited<ReturnType<typeof getAgents>>>
export type GetAgentsQueryError = ErrorType<HTTPValidationError>


export function useGetAgents<TData = Awaited<ReturnType<typeof getAgents>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  GetAgentsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAgents>>,
          TError,
          Awaited<ReturnType<typeof getAgents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAgents<TData = Awaited<ReturnType<typeof getAgents>>, TError = ErrorType<HTTPValidationError>>(
 params?: GetAgentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAgents>>,
          TError,
          Awaited<ReturnType<typeof getAgents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAgents<TData = Awaited<ReturnType<typeof getAgents>>, TError = ErrorType<HTTPValidationError>>(
 params?: GetAgentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Agents
 */

export function useGetAgents<TData = Awaited<ReturnType<typeof getAgents>>, TError = ErrorType<HTTPValidationError>>(
 params?: GetAgentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAgentsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get an agent by ID. Superuser only.

Args:
    agent_id (UUID): The agent ID.
    current_superuser (User): The current superuser.
    session (SessionDep): The database session.

Returns:
    AgentPublic: The agent.

Raises:
    HTTPException: 404 if the agent does not exist.
 * @summary Get Agent
 */
export const getAgent = (
    agentId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AgentPublic>(
      {url: `/agents/${agentId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetAgentQueryKey = (agentId: string,) => {
    return [
    `/agents/${agentId}`
    ] as const;
    }

    
export const getGetAgentQueryOptions = <TData = Awaited<ReturnType<typeof getAgent>>, TError = ErrorType<HTTPValidationError>>(agentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgent>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAgentQueryKey(agentId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAgent>>> = ({ signal }) => getAgent(agentId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(agentId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAgent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAgentQueryResult = NonNullable<Awaited<ReturnType<typeof getAgent>>>
export type GetAgentQueryError = ErrorType<HTTPValidationError>


export function useGetAgent<TData = Awaited<ReturnType<typeof getAgent>>, TError = ErrorType<HTTPValidationError>>(
 agentId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAgent>>,
          TError,
          Awaited<ReturnType<typeof getAgent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAgent<TData = Awaited<ReturnType<typeof getAgent>>, TError = ErrorType<HTTPValidationError>>(
 agentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAgent>>,
          TError,
          Awaited<ReturnType<typeof getAgent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAgent<TData = Awaited<ReturnType<typeof getAgent>>, TError = ErrorType<HTTPValidationError>>(
 agentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgent>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Agent
 */

export function useGetAgent<TData = Awaited<ReturnType<typeof getAgent>>, TError = ErrorType<HTTPValidationError>>(
 agentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgent>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAgentQueryOptions(agentId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update an agent. Superuser only.

Args:
    agent_id (UUID): The agent ID.
    agent_in (AgentUpdate): The update data.
    current_superuser (User): The current superuser.
    session (SessionDep): The database session.

Returns:
    AgentPublic: The updated agent.

Raises:
    HTTPException: 404 if the agent does not exist.
    HTTPException: 409 if the agent name is already registered.
 * @summary Update Agent
 */
export const updateAgent = (
    agentId: string,
    agentUpdate: BodyType<AgentUpdate>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AgentPublic>(
      {url: `/agents/${agentId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: agentUpdate, signal
    },
      options);
    }
  


export const getUpdateAgentMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAgent>>, TError,{agentId: string;data: BodyType<AgentUpdate>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateAgent>>, TError,{agentId: string;data: BodyType<AgentUpdate>}, TContext> => {

const mutationKey = ['updateAgent'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateAgent>>, {agentId: string;data: BodyType<AgentUpdate>}> = (props) => {
          const {agentId,data} = props ?? {};

          return  updateAgent(agentId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateAgentMutationResult = NonNullable<Awaited<ReturnType<typeof updateAgent>>>
    export type UpdateAgentMutationBody = BodyType<AgentUpdate>
    export type UpdateAgentMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Agent
 */
export const useUpdateAgent = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAgent>>, TError,{agentId: string;data: BodyType<AgentUpdate>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateAgent>>,
        TError,
        {agentId: string;data: BodyType<AgentUpdate>},
        TContext
      > => {
      return useMutation(getUpdateAgentMutationOptions(options), queryClient);
    }
    /**
 * Delete an agent. Superuser only.

Args:
    agent_id (UUID): The agent ID.
    current_superuser (User): The current superuser.
    session (SessionDep): The database session.

Raises:
    HTTPException: 404 if the agent does not exist.
 * @summary Delete Agent
 */
export const deleteAgent = (
    agentId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/agents/${agentId}`, method: 'DELETE', signal
    },
      options);
    }
  


export const getDeleteAgentMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAgent>>, TError,{agentId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAgent>>, TError,{agentId: string}, TContext> => {

const mutationKey = ['deleteAgent'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAgent>>, {agentId: string}> = (props) => {
          const {agentId} = props ?? {};

          return  deleteAgent(agentId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAgentMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAgent>>>
    
    export type DeleteAgentMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Delete Agent
 */
export const useDeleteAgent = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAgent>>, TError,{agentId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAgent>>,
        TError,
        {agentId: string},
        TContext
      > => {
      return useMutation(getDeleteAgentMutationOptions(options), queryClient);
    }
    