/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * AI Shop Helper
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Get the current authenticated user.

Args:
    current_user (User): The current authenticated user.

Returns:
    UserPublic: The current user.
 * @summary Get Me
 */
export const UsersGetMeResponse = zod.object({
  "id": zod.string().uuid(),
  "email": zod.string().email(),
  "name": zod.string(),
  "is_active": zod.boolean(),
  "is_superuser": zod.boolean(),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
}).describe('Schema for returning user data to the client.')

/**
 * Update the current authenticated user.

Args:
    user_in (UserUpdate): The update data.
    current_user (User): The current authenticated user.
    session (SessionDep): The database session.

Returns:
    UserPublic: The updated user.

Raises:
    HTTPException: 409 if the email is already registered.
 * @summary Update Me
 */
export const UsersUpdateMeBody = zod.object({
  "email": zod.union([zod.string().email(),zod.null()]).optional(),
  "name": zod.union([zod.string(),zod.null()]).optional(),
  "password": zod.union([zod.string(),zod.null()]).optional()
}).describe('Schema for updating the current user\'s own profile.')

export const UsersUpdateMeResponse = zod.object({
  "id": zod.string().uuid(),
  "email": zod.string().email(),
  "name": zod.string(),
  "is_active": zod.boolean(),
  "is_superuser": zod.boolean(),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
}).describe('Schema for returning user data to the client.')

/**
 * Get a paginated list of users. Superuser only.

Args:
    current_superuser (User): The current superuser.
    pagination (PaginationParams): The pagination parameters.
    session (SessionDep): The database session.

Returns:
    PaginatedResponse[UserPublic]: The paginated list of users.
 * @summary Get Users
 */
export const usersGetUsersQueryOffsetDefault = 0;
export const usersGetUsersQueryOffsetMin = 0;

export const usersGetUsersQueryLimitDefault = 50;
export const usersGetUsersQueryLimitMax = 100;



export const UsersGetUsersQueryParams = zod.object({
  "offset": zod.number().min(usersGetUsersQueryOffsetMin).default(usersGetUsersQueryOffsetDefault),
  "limit": zod.number().min(1).max(usersGetUsersQueryLimitMax).default(usersGetUsersQueryLimitDefault)
})

export const UsersGetUsersResponse = zod.unknown()

/**
 * Get a user by ID. Superuser only.

Args:
    user_id (UUID): The user ID.
    current_superuser (User): The current superuser.
    session (SessionDep): The database session.

Returns:
    UserPublic: The user.

Raises:
    HTTPException: 404 if the user does not exist.
 * @summary Get User
 */
export const UsersGetUserParams = zod.object({
  "user_id": zod.string().uuid()
})

export const UsersGetUserResponse = zod.object({
  "id": zod.string().uuid(),
  "email": zod.string().email(),
  "name": zod.string(),
  "is_active": zod.boolean(),
  "is_superuser": zod.boolean(),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
}).describe('Schema for returning user data to the client.')

/**
 * Update a user. Superuser only.

Args:
    user_id (UUID): The user ID.
    user_in (UserAdminUpdate): The update data.
    current_superuser (User): The current superuser.
    session (SessionDep): The database session.

Returns:
    UserPublic: The updated user.

Raises:
    HTTPException: 404 if the user does not exist.
    HTTPException: 409 if the email is already registered.
 * @summary Update User
 */
export const UsersUpdateUserParams = zod.object({
  "user_id": zod.string().uuid()
})

export const UsersUpdateUserBody = zod.object({
  "email": zod.union([zod.string().email(),zod.null()]).optional(),
  "name": zod.union([zod.string(),zod.null()]).optional(),
  "password": zod.union([zod.string(),zod.null()]).optional(),
  "is_active": zod.union([zod.boolean(),zod.null()]).optional(),
  "is_superuser": zod.union([zod.boolean(),zod.null()]).optional()
}).describe('Schema for superuser updating any user.')

export const UsersUpdateUserResponse = zod.object({
  "id": zod.string().uuid(),
  "email": zod.string().email(),
  "name": zod.string(),
  "is_active": zod.boolean(),
  "is_superuser": zod.boolean(),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
}).describe('Schema for returning user data to the client.')

/**
 * Delete a user. Superuser only.

Args:
    user_id (UUID): The user ID.
    current_superuser (User): The current superuser.
    session (SessionDep): The database session.

Raises:
    HTTPException: 400 if the superuser tries to delete itself.
    HTTPException: 404 if the user does not exist.
 * @summary Delete User
 */
export const UsersDeleteUserParams = zod.object({
  "user_id": zod.string().uuid()
})

